kind: Deployment
apiVersion: apps/v1
metadata:
  name: bts-web-dev
  labels:
    app: bts-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bts-web
      role: web
      env: dev
  template:
    metadata:
      name: web
      labels:
        app: bts-web
        role: web
        env: dev
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: credentials-key
      containers:
      - name: bts-web
        image: gcr.io/hybrid-bts/bts-web
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        ports:
        - name: web
          containerPort: 80
