apiVersion: v1
kind: Service
metadata:
  name: bts-web-service
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: bts-web
spec:
  type: LoadBalancer
  selector:
    app: bts-web
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
